version: 2.1

executors:
  rust:
    docker:
      - image: circleci/rust:1.37

jobs:
  clippy:
    executor: rust
    steps:
      - run: rustup component add clippy
      - checkout
      - run: cargo clippy --all-targets

  test:
    executor: rust
    steps:
      - checkout
      - run: cargo test --all-targets

  publish:
    executor: rust
    steps:
      - checkout
      - run: sed -i 's/^version\s*=.*$/version = "'$(echo $CIRCLE_TAG | sed -nre 's/^v(.*)$/\1/p')'"/' Cargo.toml
      - run: cargo publish --allow-dirty

workflows:
  version: 2
  main:
    jobs:
      - clippy:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: cargo-publish
          requires: [clippy, test]
          filters:
            branches:
              ignore: /.*/
            tags:
              # v1.0.0
              only: /^v\d+\.\d+\.\d+$/
